// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdQLeoeDzQPRgR8j0_ndLVljB4h480DU',
    appId: '1:888933399257:android:b8daea61eecb4f789e1cc8',
    messagingSenderId: '888933399257',
    projectId: 'toto-bb516',
    storageBucket: 'toto-bb516.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhFTUP7p1QnKigm6MA7iDcoMv-7BY_wlE',
    appId: '1:888933399257:web:0db45987523b5d799e1cc8',
    messagingSenderId: '888933399257',
    projectId: 'toto-bb516',
    authDomain: 'toto-bb516.firebaseapp.com',
    storageBucket: 'toto-bb516.firebasestorage.app',
    measurementId: 'G-E9S4E9218L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdJj-rpfG4et4Nk3F8-0vyZN6yylRpUYU',
    appId: '1:888933399257:ios:83a00e5818f80eab9e1cc8',
    messagingSenderId: '888933399257',
    projectId: 'toto-bb516',
    storageBucket: 'toto-bb516.firebasestorage.app',
    iosBundleId: 'com.example.tot',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdJj-rpfG4et4Nk3F8-0vyZN6yylRpUYU',
    appId: '1:888933399257:ios:83a00e5818f80eab9e1cc8',
    messagingSenderId: '888933399257',
    projectId: 'toto-bb516',
    storageBucket: 'toto-bb516.firebasestorage.app',
    iosBundleId: 'com.example.tot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhFTUP7p1QnKigm6MA7iDcoMv-7BY_wlE',
    appId: '1:888933399257:web:6f6ea95b2f324fb79e1cc8',
    messagingSenderId: '888933399257',
    projectId: 'toto-bb516',
    authDomain: 'toto-bb516.firebaseapp.com',
    storageBucket: 'toto-bb516.firebasestorage.app',
    measurementId: 'G-V9YWV7E2VQ',
  );

}